version: "3.9"
   
services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=EmployeeDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dip#postgres
             
 